version: '3'
services:
  web:
    build: .
    ports:
     - "3000:3000"
    depends_on:
      - redis
    networks:
      my_net:
        ipv4_address: 172.20.0.2
  redis:
    image: "redis:alpine"
    networks:
      my_net:
        ipv4_address: 172.20.0.3
networks:
  my_net:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"